### ISSUE TITLE
Add contact information

### ISSUE THREAD

**Issue by aderchox** [nimaes80/nimaes80#1]
Hi Nima, I see you've said you'd like to learn from people but you've not included any contact information. So wanted to recommend you add some (idk, maybe at least an email) in there so people can connect with you more easily. Have a nice life 👋.

**Comment by bambier** [comment]
Hi @aderchox  I cant because of security reason, however if there is any thing some one wants to ask/answer they can send them here, I answer as soon as I can.

Best wishes.

**Comment by aderchox** [comment]
That's weird, you could create an email with any made up names and put it on your account as your contact information and no one will find out who you are, anyways I won't insist, it's your own choice :).
